### ISSUE TITLE
Set does not support writing flags

### ISSUE THREAD

**Issue by dblock** [alevy/memjs#50] opened 2014-09-10 21:34 UTC
Flags is being retrieved and is the third parameter of the `get` callback. Flags is an arbitrary 32-bit unsigned integer (written out in decimal) that the server stores along with the data and sends back when the item is retrieved. Clients may use this as a bit field to store data-specific information; this field is opaque to the server. 

Memjs should support setting it as well.

**Comment by alevy** [comment] 2015-09-20 16:37
Duplicate of #53

**Closed by alevy** 2015-09-20 16:37 UTC
